apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sidecar 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar 
    spec:
      containers:
        - name: sidecar 
          image: saxo01.azurecr.io/sidecar
          ports:
          - containerPort: 80