apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: demoapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapi 
    spec:
      containers:
        - name: demoapi 
          image: saxo01.azurecr.io/demoapi
          ports:
          - containerPort: 81